ajm/rhel install steps
CARTAvis/carta-node-server pull request #104
Opened 2021-12-07 07:18 UTC by ajm-asiaa

Here is a step-by-step guide for AlmaLinux. I guess you may want some changes made.

2021-12-08 06:52 UTC, veggiesaurus requested changes
Some minor adjustments

2021-12-08 06:52 UTC, veggiesaurus commented on docs/src/almalinux_instructions.rst
> +    Beta versions of carta-controller can be installed. For example, ``sudo npm install -g --unsafe-perm carta-controller-3.0.0-beta.1d``.
perhaps we should just say `carta-controller@beta` instead of specifying an exact version?

2021-12-08 06:52 UTC, veggiesaurus commented on docs/src/almalinux_instructions.rst
> +    # Check that the backend can run and is version 2.0.0
I'd say "and matches the major version number of the controller"

2021-12-08 06:52 UTC, veggiesaurus commented on docs/src/almalinux_instructions.rst
> +    # Generate private/public keys (optional if you do not already have SSL certificates):
the private/public keys in `/etc/carta` are not related to nginx. They're used by carta-controller to sign/verify refresh and access tokens. Rather move this section to the controller configuration part

2021-12-08 06:52 UTC, veggiesaurus commented on docs/src/almalinux_instructions.rst
> +    carta-controller -v -t bob
can we use `--verbose --test` here, just so its clear what it's doing?

2021-12-08 06:52 UTC, veggiesaurus commented on docs/src/almalinux_instructions.rst
> +With PAM authentication, the ``carta`` user that runs carta-controller requires access to the ``/etc/shadow`` file in order to authenticate other users. We can enable this by creating a new group cal
I think it's worth clarifying that you only need `/etc/shadow` access when using PAM with local authentication. PAM using LDAP doesn't require this.

2021-12-08 06:52 UTC, veggiesaurus commented on docs/src/almalinux_instructions.rst
> +10. Set up carta-controller to run with pm2
Mark this as optional?

2021-12-09 03:45 UTC, ajm-asiaa commented
@veggiesaurus Thanks for the comments. Do we also need the web server to use HTTPS? So it also needs to be configured with valid SSL certificates?

2021-12-09 07:08 UTC, veggiesaurus commented
> @veggiesaurus Thanks for the comments. Do we also need the web server to use HTTPS? So it also needs to be configured with valid SSL certificates?

You can run the controller behind an HTTP-only reverse proxy, but then you need to use the `httpOnly` setting in the config file. But this should really only be done during testing.

2021-12-09 09:37 UTC, confluence requested changes

2021-12-09 09:37 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +Step-by-step instructions for Almalinux 8.4
AlmaLinux needs a capital L.

2021-12-09 09:37 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +    These instructions should also work for RHEL8, CentOS8, and Rocky Linux. Some changes may be necessary for RHEL7/CenOS7.
Typo: CenOS7 -> CentOS7

2021-12-09 09:37 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +carta-controller uses `Node.js <https://nodejs.org/>`_ and supports v12, v14, and v16. Node.js can easily be installed from the AlmaLinux AppStream repository. Here we install v14, as well as the ``n
"carta-controller" should be replaced with "the CARTA controller" here and in other places in this document.

2021-12-09 09:37 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +carta-controller uses `MongoDB <https://www.mongodb.com/>`_ to store user preferences etc. MongoDB is not available through the default AlmaLinux repositories, but we can create to custom repository
"preferences etc." -> "preferences, etc.."
"we can create to custom repository file in order to easily install it" -> "we can add a custom repository to install it more easily"

2021-12-09 09:37 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +4. Install the carta-backend component
"carta-backend" or "the carta-backend component" should be replaced with "the CARTA backend".

2021-12-09 09:37 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +    If you install the beta version of carta-controller, you need to install the beta version of the carta-backend ``sudo dnf -y install carta-backend-beta``.
This entire document should be just for the beta version, and contain all the correct version names -- it should be backported to the release branch with different version names.

2021-12-09 09:37 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +    If there are problems, you can debug with ``journactl -xe`` and checking log files in ``/var/log/nginx/``.
"by checking..."

2021-12-09 09:37 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +We will allow any user in the ``carta-users`` group to run ``/usr/bin/carta_backend`` and the script to close the carta-backend; ``/usr/local/bin/carta-kill-script`` by adding a custom entry to the `
The carta user should not be in the carta-users group; that's for the user accounts.

2021-12-09 09:37 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +This is the most difficult step and depends how you authenticate users at your institute.
depends on

Delete the newline after the first sentence.

2021-12-09 09:37 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +    Only PAM with local authentication requires /etc/shadow access. PAM using LDAP, and Google OAuth, do not require /etc/shadow access.
`/etc/shadow` should be formatted as code.

2021-12-09 09:37 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +Create and fill in the ``config.json`` using our sample file :ref:`sample configuration file<example_config>`.
"sample file" is redundant; URL text is provided with the URL

2021-12-09 10:26 UTC, ajm-asiaa commented
@confluence Thanks for the corrections and clarifying that user `carta` should not be part of the `carta-users` group!

2021-12-09 11:48 UTC, confluence requested changes
This section needs to be added to the documentation index TOC; it currently isn't linked from anything. The text at the beginning of the index should also be edited to mention and link to both sets of detailed instructions.

Are we officially supporting AlmaLinux? If yes, it should be listed explicitly in the list of distros that we support.

The RPM repository should also be mentioned in the installation section (the backend subsection), and this section should be linked from there. I suggest splitting that subsection up further into sub-subsections called `Debian packages`, `RPM packages` and `Source`.

2021-12-09 11:48 UTC, confluence commented on docs/src/almalinux_instructions.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This underline needs to be adjusted to match the new heading text (Sphinx warns about it).

2021-12-09 12:01 UTC, veggiesaurus commented
> Are we officially supporting AlmaLinux? If yes, it should be listed explicitly in the list of distros that we support.

I guess we officially support RHEL8 and CentOS 8. Isn't AlmaLinux basically the same thing?

2021-12-09 12:10 UTC, ajm-asiaa commented
It is tricky. CentOS8 is turning into CentOS Stream next month, so maybe we can not mention CentOS8 anymore. RHEL8 is a bit awkward to use because you generally need to pay for a subscription. The new 'free' 1:1 binary compatible equivalents to RHEL are AlmaLinux and Rocky Linux.

2021-12-10 08:33 UTC, veggiesaurus approved these changes

2021-12-10 08:33 UTC, merged